<?php
$pageName = basename(__FILE__, '.php');
APIInfoPageStart($pageName, "Retrieves all available device IDs against staff id.");
?>
        <tbody>
            <tr><td>Endpoint</td><td><code><?php echo $pageName;?></code></td></tr>
            <tr><td>Method</td><td><strong>POST</strong></td></tr>
            <tr><td>Request</td><td><details><summary><strong>Sample Request</strong></summary>
<pre>
{
  "outletId":5
}
</pre>
        </details></td></tr>
            <tr><td>Response</td><td><details><summary><strong>Sample response</strong></summary>
<pre>
{
    "status": true,
    "value": "result found",
    "services": [
        {
            "id": "68",
            "title": "I want NewsPaper",
            "userId": "5",
            "boxId": "3",
            "serviceId": "32",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": null,
            "information": "",
            "reminderTime": "3",
            "escalationTime": "5",
            "priority": "High",
            "points": "4",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-07-04 16:18:02",
            "updated_date": "2022-12-04 16:12:44"
        },
        {
            "id": "113",
            "title": "Send Luggage Boy",
            "userId": "5",
            "boxId": "3",
            "serviceId": "31",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": null,
            "information": "charges according to weight",
            "reminderTime": "3",
            "escalationTime": "5",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-07-06 13:52:15",
            "updated_date": "2022-07-06 13:52:32"
        },
        {
            "id": "283",
            "title": "SPA",
            "userId": "5",
            "boxId": "6",
            "serviceId": "35",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": null,
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "YES",
            "status": "YES",
            "created_date": "2022-12-17 22:36:11",
            "updated_date": "2022-12-17 22:36:11"
        },
        {
            "id": "325",
            "title": "Doctor on call",
            "userId": "5",
            "boxId": "2",
            "serviceId": "37",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "0",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Urgent",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2023-02-18 15:52:02",
            "updated_date": "2023-02-18 15:52:02"
        },
        {
            "id": "326",
            "title": "Call front office",
            "userId": "5",
            "boxId": "2",
            "serviceId": "30",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "0",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Urgent",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2023-02-18 15:52:52",
            "updated_date": "2023-02-18 15:52:52"
        },
        {
            "id": "21",
            "title": "Shaving Kit & Dental Kit (Chargeble)",
            "userId": "5",
            "boxId": "4",
            "serviceId": "7",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "2",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:50:22",
            "updated_date": "2022-06-29 13:10:41"
        },
        {
            "id": "20",
            "title": "Plumbing",
            "userId": "5",
            "boxId": "5",
            "serviceId": "27",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "3",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:50:10",
            "updated_date": "2022-06-29 13:11:07"
        },
        {
            "id": "19",
            "title": "Pickup up My Laundry",
            "userId": "5",
            "boxId": "2",
            "serviceId": "4",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "4",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:49:54",
            "updated_date": "2022-06-29 13:11:34"
        },
        {
            "id": "18",
            "title": "Order Food",
            "userId": "5",
            "boxId": "1",
            "serviceId": "1",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "5",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:49:37",
            "updated_date": "2022-06-29 13:11:47"
        },
        {
            "id": "17",
            "title": "Need towel 123",
            "userId": "5",
            "boxId": "2",
            "serviceId": "5",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "6",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:49:25",
            "updated_date": "2023-02-17 15:33:43"
        },
        {
            "id": "25",
            "title": "Wakeup Call",
            "userId": "5",
            "boxId": "3",
            "serviceId": "14",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "6",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:52:01",
            "updated_date": "2022-06-29 13:12:19"
        },
        {
            "id": "3",
            "title": "Call front office",
            "userId": "5",
            "boxId": "3",
            "serviceId": "30",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "7",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:45:05",
            "updated_date": "2022-06-29 13:12:29"
        },
        {
            "id": "16",
            "title": "Need room freshener",
            "userId": "5",
            "boxId": "2",
            "serviceId": "21",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "7",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:49:09",
            "updated_date": "2022-06-29 13:12:45"
        },
        {
            "id": "24",
            "title": "Toiletries like soap/ shampoo etc.",
            "userId": "5",
            "boxId": "4",
            "serviceId": "22",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "7",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:51:51",
            "updated_date": "2022-06-29 13:12:54"
        },
        {
            "id": "8",
            "title": "Clean my room",
            "userId": "5",
            "boxId": "2",
            "serviceId": "2",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "8",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:47:15",
            "updated_date": "2022-06-29 13:13:01"
        },
        {
            "id": "23",
            "title": "Sugar & Tea Packet",
            "userId": "5",
            "boxId": "4",
            "serviceId": "6",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "8",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:51:25",
            "updated_date": "2022-06-29 13:13:09"
        },
        {
            "id": "14",
            "title": "I want to check out",
            "userId": "5",
            "boxId": "3",
            "serviceId": "19",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "9",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:48:46",
            "updated_date": "2022-06-29 13:14:04"
        },
        {
            "id": "22",
            "title": "Shoe Shiner",
            "userId": "5",
            "boxId": "4",
            "serviceId": "10",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "9",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:51:12",
            "updated_date": "2022-06-29 13:13:16"
        },
        {
            "id": "13",
            "title": "I want GST Bill",
            "userId": "5",
            "boxId": "3",
            "serviceId": "20",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "10",
            "information": "",
            "reminderTime": "3",
            "escalationTime": "10",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:48:33",
            "updated_date": "2022-06-29 13:07:16"
        },
        {
            "id": "12",
            "title": "I need crockery / Cutlery",
            "userId": "5",
            "boxId": "4",
            "serviceId": "24",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "11",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:48:20",
            "updated_date": "2022-06-29 13:07:31"
        },
        {
            "id": "2",
            "title": "Bottled Water",
            "userId": "5",
            "boxId": "5",
            "serviceId": "26",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "12",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:44:50",
            "updated_date": "2022-06-29 13:09:11"
        },
        {
            "id": "15",
            "title": "I want to continue my stay",
            "userId": "5",
            "boxId": "3",
            "serviceId": "18",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "13",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:48:56",
            "updated_date": "2022-06-29 13:09:24"
        },
        {
            "id": "11",
            "title": "First aid Kit",
            "userId": "5",
            "boxId": "4",
            "serviceId": "8",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "14",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:47:54",
            "updated_date": "2022-06-29 13:09:33"
        },
        {
            "id": "10",
            "title": "Electrical",
            "userId": "5",
            "boxId": "5",
            "serviceId": "28",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "15",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:47:41",
            "updated_date": "2022-06-29 13:09:41"
        },
        {
            "id": "4",
            "title": "Carpentry",
            "userId": "5",
            "boxId": "5",
            "serviceId": "29",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "16",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:46:05",
            "updated_date": "2022-06-29 13:09:52"
        },
        {
            "id": "28",
            "title": "Taxi Service",
            "userId": "5",
            "boxId": "3",
            "serviceId": "15",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "17",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "3",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-25 14:29:57",
            "updated_date": "2022-07-06 21:08:02"
        },
        {
            "id": "5",
            "title": "Change My Linen",
            "userId": "5",
            "boxId": "2",
            "serviceId": "3",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "18",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "3",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:46:20",
            "updated_date": "2022-06-29 13:10:08"
        },
        {
            "id": "27",
            "title": "WIFI issue",
            "userId": "5",
            "boxId": "2",
            "serviceId": "13",
            "actionBy": "FO",
            "aksDateTime": "NO",
            "sq": "19",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:52:24",
            "updated_date": "2022-06-29 13:10:16"
        },
        {
            "id": "26",
            "title": "Water Bottle",
            "userId": "5",
            "boxId": "5",
            "serviceId": "9",
            "actionBy": "HK",
            "aksDateTime": "NO",
            "sq": "21",
            "information": "",
            "reminderTime": "0",
            "escalationTime": "0",
            "priority": "Medium",
            "points": "1",
            "onHoldOption": "NO",
            "status": "YES",
            "created_date": "2022-06-23 09:52:14",
            "updated_date": "2022-06-29 13:11:00"
        }
    ]
}
</pre></details></td>
            </tr>
        </tbody>
<?php APIInfoPageEnd(); ?>
